### ISSUE TITLE
How to set previous step?

### ISSUE THREAD

**Issue by yogeshshsf** [domske/state-stepper#4]
Hi, 

i have three steps. currently i am in step3 and i have to navigate to step 2. how can i achieve this?.
from step2 to step1 i can naviagate by calling this.stepper.reset() method. 
thanks in advance

**Comment by domske** [comment]
Thanks for your feedback.
You have full control over your steps. The methods are only optional. Each step has following interface: 

```ts
export interface Step {
  icon: string;
  text?: string;
  state?: string;
  active?: boolean;
}
```
States: `success`, `warning`, `error`. 

Currently there is no step back method. You can only reset. (or access the state of your steps manually).
This component is experimental. See readme.md for more infos. 
It is planned to complete this  component in the futur. Ionic 4 support, documentation, etc.

**Comment by domske** [comment]
State-Stepper is now a Web-Component. [Read more](https://github.com/domske/state-stepper) It's now possible to step backwards.
